version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      BOT_USERNAME: $BOT_USERNAME
      BOT_NAME: $BOT_NAME
      ASSISTANT_NAME: $ASSISTANT_NAME
      SESSION_NAME: $SESSION_NAME
      SUDO_USERS: $SUDO_USERS
      GROUP_SUPPORT: $GROUP_SUPPORT
      UPDATES_CHANNEL: $UPDATES_CHANNEL
      OWNER_NAME: $OWNER_NAME
      ALIVE_NAME: $ALIVE_NAME
